### PR TITLE
Livewire 2 + Laravel 8 support

### PR DESCRIPTION
**Pull request by da-sie**

### CODE REVIEW

**Comment by da-sie** [comment]
Adresses #3

**Comment by barryvdh** [comment]
@naszybko are no other changes required, did you test this already?

@asantibanez Are there any blockers?

**Comment by asantibanez** [comment]
Thanks @naszybko @barryvdh for the help on this one. 

Looks like a quick add. Have you tested this change @naszybko ? Will try it out today and publish a new release if it's all that's needed to support Livewire v2 and Laravel 8.

**Comment by barryvdh** [comment]
Cool, Will you also update https://github.com/asantibanez/livewire-resource-time-grid ? Haven't tried it yet with v2

**Comment by barryvdh** [comment]
I think the same as https://github.com/asantibanez/livewire-resource-time-grid/pull/4 also applied here, the blade directive should be in boot, not register.

**Pull request merged**
